### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by stewid**

### CODE REVIEW

**Comment by stewid** [comment]
I think it is `--configure-args`, see the example in https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Configure-example

**Comment by jeroenooms** [comment]
The manual page for `R CMD INSTALL --help` says:

```
      --configure-args=ARGS
			set arguments for the configure scripts (if any)
      --configure-vars=VARS
			set variables for the configure scripts (if any)
```

This configure script does not actually parse script arguments, it only uses environment variables. I just tested it by running:

```
R CMD INSTALL openssl_0.8.tar.gz --configure-vars='INCLUDE_DIR=/FOOBAR LIB_DIR=/FOOBAR'
```

And this does the expected thing:

```
Found INCLUDE_DIR and/or LIB_DIR!
Using PKG_CFLAGS=-I/FOOBAR
Using PKG_LIBS=-L/FOOBAR -lssl -lcrypto
```

Is it not working for you?

**Comment by jeroenooms** [comment]
I'm quite sure this is correct :) Feel free to open an issue if something is not working for you!

**Comment by stewid** [comment]
Thanks for the explanation. I was not aware of `--configure-vars` and did not think of the difference between arguments to a configure script and autoconf scripts. I just assumed it was a typo when I read it, without actually testing :-) 

I get the same result as you when I run
```
R CMD INSTALL openssl_0.8.tar.gz --configure vars='INCLUDE_DIR=/FOOBAR LIB_DIR=/FOOBAR'
```

Cheers

**Pull request closed without merging**
